server:
  port: 7200
  servlet:
    context-path: /api
spring:
  application:
    name: shesg
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/shesg?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: dhgatesz_123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

openai:
  api-key: you_api_key